In [1]:
import sys
sys.path.append('..')

import progressions as prog
import pandas as pd

In [2]:
primes = pd.read_csv('../primes_100.csv')

primeList = primes['primes'].tolist()

primes.head(10)

   primes
0       2
1       3
2       5
3       7
4      11
5      13
6      17
7      19
8      23
9      29

In [3]:
result_dict = dict()

for k in range(2, 212, 2):
    res = prog.llap(primeList, k)
    result_dict[k] = res
    
# prev best 8m 22.2s

In [5]:
df = pd.DataFrame(result_dict).head(20)
df.head(20)

,2,4,6,8,10,12,14,16,18,20,...,192,194,196,198,200,202,204,206,208,210
length,2,2,4,2,2,4,2,2,4,2,...,4,2,2,4,2,2,4,2,2,10
step,2,4,6,8,10,12,14,16,18,20,...,192,194,196,198,200,202,204,206,208,210
total,440310,440257,9329,439906,586810,9454,528093,441054,9412,586266,...,9409,444890,529086,13341,587376,444963,11614,444239,480309,1

In [6]:
df.to_csv(path_or_buf='../progressionsBeta.csv')